// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLrfcFg-hTLWPZAPkuUNmeM8axd0qWgq4',
    appId: '1:994866531889:web:6ef5b24df3f22c6b7e4f10',
    messagingSenderId: '994866531889',
    projectId: 'quizapp-e5ce1',
    authDomain: 'quizapp-e5ce1.firebaseapp.com',
    storageBucket: 'quizapp-e5ce1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHhtA7b5WQ9ksGiASu0rkZPWmYaeuAQ4',
    appId: '1:994866531889:android:444732387c648f727e4f10',
    messagingSenderId: '994866531889',
    projectId: 'quizapp-e5ce1',
    storageBucket: 'quizapp-e5ce1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaFsapGaNNz0APj3XvPrXm9lMXnWBeDqA',
    appId: '1:994866531889:ios:e4c32c51ab9b52767e4f10',
    messagingSenderId: '994866531889',
    projectId: 'quizapp-e5ce1',
    storageBucket: 'quizapp-e5ce1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaFsapGaNNz0APj3XvPrXm9lMXnWBeDqA',
    appId: '1:994866531889:ios:e4c32c51ab9b52767e4f10',
    messagingSenderId: '994866531889',
    projectId: 'quizapp-e5ce1',
    storageBucket: 'quizapp-e5ce1.firebasestorage.app',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLrfcFg-hTLWPZAPkuUNmeM8axd0qWgq4',
    appId: '1:994866531889:web:59d702ce0b99e47a7e4f10',
    messagingSenderId: '994866531889',
    projectId: 'quizapp-e5ce1',
    authDomain: 'quizapp-e5ce1.firebaseapp.com',
    storageBucket: 'quizapp-e5ce1.firebasestorage.app',
  );
}
